/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booksort;

import static booksort.Sorting.bookList;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Caleb
 */
public class NewGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewGUI
     */
    public NewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    String tmpString = "";
    Boolean currentTheme = true;
    Boolean tableEditable = false;
    Object[] tmpArr = {null, null, null, null, null, null};
    String[] tmpStrArr = {null, null, null, null, null, null};
    String s1 = "";
    String s2 = "";
    String s3 = "";
    String s4 = "";
    String s5 = "";
    String s6 = "";
    int highestInt = 0;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        bookTable.setEnabled(false);
        jButton2 = new javax.swing.JButton();
        jButton2.putClientProperty( "JButton.buttonType", "help" );
        themeButton = new javax.swing.JButton();
        titleSearch = new javax.swing.JTextField();
        authorSearch = new javax.swing.JTextField();
        genreSearch = new javax.swing.JTextField();
        ISBNSearch = new javax.swing.JTextField();
        editButton = new javax.swing.JToggleButton();
        refreshButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bookTable.setAutoCreateRowSorter(true);
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", null, null}
            },
            new String [] {
                "Title", "Author", "Genre", "ISBN", "Availability", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setShowHorizontalLines(true);
        bookTable.setShowVerticalLines(true);
        bookTable.getTableHeader().setReorderingAllowed(false);
        //DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
        //        model.setRowCount(0);
        //        for (int i = 0; i < bookList.size(); i++){
            //            bookList.get(i);
            //            Object[] tmpArr = {bookList.get(i)[0], bookList.get(i)[1], bookList.get(i)[2], bookList.get(i)[3], Boolean.parseBoolean(bookList.get(i)[4]), Integer.valueOf(bookList.get(i)[5])};
            //            model.addRow(tmpArr);
            //            bookList.get(i);
            //        }
        try {
            Sorting.ID = 0;
            FileReader freader = new FileReader("books.txt");
            BufferedReader reader = new BufferedReader(freader);
            bookList.clear();
            while (tmpString != null) {
                tmpString = reader.readLine();
                if (tmpString != null){
                    String[] tmpStrArr = tmpString.replace("[", "").replace("]", "").split(", ");
                    bookList.add(tmpStrArr);
                    Sorting.ID++;
                }
            }
            reader.close();
            tmpString = "";
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < bookList.size(); i++){
            bookList.get(i);
            Object[] tmpArr = {bookList.get(i)[0], bookList.get(i)[1], bookList.get(i)[2], bookList.get(i)[3], Boolean.parseBoolean(bookList.get(i)[4]), Integer.valueOf(bookList.get(i)[5])};
            model.addRow(tmpArr);
            bookList.get(i);
        }
        bookTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookTableFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setResizable(false);
            bookTable.getColumnModel().getColumn(1).setResizable(false);
            bookTable.getColumnModel().getColumn(2).setResizable(false);
            bookTable.getColumnModel().getColumn(3).setResizable(false);
            bookTable.getColumnModel().getColumn(4).setResizable(false);
            bookTable.getColumnModel().getColumn(5).setResizable(false);
            bookTable.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        themeButton.setBackground(new java.awt.Color(0, 0, 1));
        themeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themeButtonMouseClicked(evt);
            }
        });
        themeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeButtonActionPerformed(evt);
            }
        });

        titleSearch.setToolTipText("Search by Title");
        titleSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                titleSearchPropertyChange(evt);
            }
        });
        titleSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleSearchKeyPressed(evt);
            }
        });

        authorSearch.setToolTipText("Search by Author");

        genreSearch.setToolTipText("Search by Genre");

        ISBNSearch.setToolTipText("Search by ISBN");

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/editLight.png"))); // NOI18N
        editButton.setToolTipText("Enable Table Editing");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/refreshLight.png"))); // NOI18N
        refreshButton.setToolTipText("Refresh Table");
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/searchLight.png"))); // NOI18N
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/saveLight.png"))); // NOI18N
        saveButton.setToolTipText("Save Table to File");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/addLight.png"))); // NOI18N
        addButton.setEnabled(false);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/removeLight.png"))); // NOI18N
        removeButton.setEnabled(false);
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/userLight.png"))); // NOI18N
        usersButton.setText(" Users");
        usersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersButtonMouseClicked(evt);
            }
        });

        checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/checkoutLight.png"))); // NOI18N
        checkOutButton.setText("Check out");
        checkOutButton.setEnabled(false);
        checkOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutButtonMouseClicked(evt);
            }
        });
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(themeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkOutButton))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genreSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISBNSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(authorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genreSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ISBNSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themeButtonMouseClicked
        if (currentTheme == false) {    // If dark mode
            FlatMacLightLaf.setup();
            com.formdev.flatlaf.FlatLaf.updateUI();
            themeButton.setBackground(Color.black);
            editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/editLight.png")));
            refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/refreshLight.png")));
            searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/searchLight.png")));
            saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/saveLight.png")));
            addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/addLight.png")));
            removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/removeLight.png")));
            checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/checkoutLight.png")));
            usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/userLight.png")));
            currentTheme = true;
        } else {                        // If light mode
            FlatMacDarkLaf.setup();
            com.formdev.flatlaf.FlatLaf.updateUI();
            themeButton.setBackground(Color.white);
            editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/editDark.png")));
            refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/refreshDark.png")));
            searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/searchDark.png")));
            saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/saveDark.png")));
            addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/addDark.png")));
            removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/removeDark.png")));
            checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/checkoutDark.png")));
            usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksort/userDark.png")));
            currentTheme = false;
        }
    }//GEN-LAST:event_themeButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void themeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (!editButton.isSelected()) {
            bookTable.clearSelection();
            bookTable.setEnabled(false);
            tableEditable = false;
            addButton.setEnabled(false);
            removeButton.setEnabled(false);
            saveButton.setEnabled(true);
            checkOutButton.setEnabled(false);
        } else {
            bookTable.clearSelection();
            bookTable.setEnabled(true);
            tableEditable = true;
            addButton.setEnabled(true);
            removeButton.setEnabled(true);
            saveButton.setEnabled(false);
            checkOutButton.setEnabled(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        if (!editButton.isSelected()) {
            bookTable.clearSelection();
            bookTable.setEnabled(false);
            if (bookTable.isEditing()){ 
                bookTable.getCellEditor().stopCellEditing();
            }
            tableEditable = false;
            addButton.setEnabled(false);
            removeButton.setEnabled(false);
            saveButton.setEnabled(true);
        } else {
            bookTable.clearSelection();
            bookTable.setEnabled(true);
            tableEditable = true;
            addButton.setEnabled(true);
            removeButton.setEnabled(true);
            saveButton.setEnabled(false);
        }
    }//GEN-LAST:event_editButtonMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        try {
            Sorting.ID = 0;
            FileReader freader = new FileReader("books.txt");
            BufferedReader reader = new BufferedReader(freader);
            bookList.clear();
            while (tmpString != null) {
		tmpString = reader.readLine();
                if (tmpString != null){
                    String[] tmpStrArr = tmpString.replace("[", "").replace("]", "").split(", ");
                    bookList.add(tmpStrArr);
                    Sorting.ID++;
                }
            }
            reader.close();
            tmpString = "";
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < bookList.size(); i++){
            bookList.get(i);
            Object[] tmpArr = {bookList.get(i)[0], bookList.get(i)[1], bookList.get(i)[2], bookList.get(i)[3], Boolean.parseBoolean(bookList.get(i)[4]), Integer.valueOf(bookList.get(i)[5])};
            model.addRow(tmpArr);
            bookList.get(i);
        }
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void titleSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleSearchKeyPressed
        
    }//GEN-LAST:event_titleSearchKeyPressed

    private void titleSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_titleSearchPropertyChange
        
    }//GEN-LAST:event_titleSearchPropertyChange

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < bookList.size(); i++){
            if ((bookList.get(i)[0].toLowerCase().contains(titleSearch.getText().toLowerCase()) || titleSearch.getText().compareTo("") == 0) &&
            (bookList.get(i)[1].toLowerCase().contains(authorSearch.getText().toLowerCase()) || authorSearch.getText().compareTo("") == 0) &&     
            (bookList.get(i)[2].toLowerCase().contains(genreSearch.getText().toLowerCase()) || genreSearch.getText().compareTo("") == 0) &&    
            (bookList.get(i)[3].toLowerCase().contains(ISBNSearch.getText().toLowerCase()) || ISBNSearch.getText().compareTo("") == 0)){
                bookList.get(i);
                Object[] tmpArr = {bookList.get(i)[0], bookList.get(i)[1], bookList.get(i)[2], bookList.get(i)[3], Boolean.parseBoolean(bookList.get(i)[4]), Integer.valueOf(bookList.get(i)[5])};
                model.addRow(tmpArr);
                bookList.get(i);
            }
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        bookTable.setEnabled(false);
        bookTable.clearSelection();
        tableEditable = false;
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to overwrite the file?", "Save", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            bookList.clear();
            for (int i = 0; i < bookTable.getRowCount(); i++){
                String[] tmpStrArr = {bookTable.getValueAt(i, 0).toString(), bookTable.getValueAt(i, 1).toString(), bookTable.getValueAt(i, 2).toString(), bookTable.getValueAt(i, 3).toString(), bookTable.getValueAt(i, 4).toString(), bookTable.getValueAt(i, 5).toString()};
                bookList.add(tmpStrArr);
            }
            
            try {
                File booksFile = new File("books.txt");
                booksFile.delete();
                OutputStreamWriter osWriter = new OutputStreamWriter(new FileOutputStream("books.txt"), "UTF-8");
                BufferedWriter bWriter = new BufferedWriter(osWriter);
                for(String[] str: bookList) {
                    bWriter.write(Arrays.toString(str) + System.lineSeparator());
                }
                bWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        bookList.clear();
            for (int i = 0; i < bookTable.getRowCount(); i++){
                String[] tmpStrArr = {bookTable.getValueAt(i, 0).toString(), bookTable.getValueAt(i, 1).toString(), bookTable.getValueAt(i, 2).toString(), bookTable.getValueAt(i, 3).toString(), bookTable.getValueAt(i, 4).toString(), bookTable.getValueAt(i, 5).toString()};
                bookList.add(tmpStrArr);
            }
            
            try {
                File booksFile = new File("books.tmp");
                booksFile.delete();
                OutputStreamWriter osWriter = new OutputStreamWriter(new FileOutputStream("books.tmp"), "UTF-8");
                BufferedWriter bWriter = new BufferedWriter(osWriter);
                for(String[] str: bookList) {
                    bWriter.write(Arrays.toString(str) + System.lineSeparator());
                }
                bWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        if (addButton.isEnabled()){
            
            try { Sorting.ID = 0;
                highestInt = 0;
                FileReader freader = new FileReader("books.tmp");
                BufferedReader reader = new BufferedReader(freader);
                bookList.clear();
                while (tmpString != null) {
                    tmpString = reader.readLine();
                    if (tmpString != null){
                        String[] tmpStrArr = tmpString.replace("[", "").replace("]", "").split(", ");
                        if (Integer.parseInt(tmpStrArr[5]) > highestInt){
                            highestInt = Integer.parseInt(tmpStrArr[5]);
                        }
                        Sorting.ID++;
                    }
                }
                if (highestInt > Sorting.ID){
                    Sorting.ID = highestInt + 1;
                } else {
                    Sorting.ID++;
                }
                reader.close();
                tmpString = "";
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
            Object[] tmpArr = {"", "", "", "", true, Sorting.ID++};
            model.addRow(tmpArr);
            
            bookList.clear();
            for (int i = 0; i < bookTable.getRowCount(); i++){
                String[] tmpStrArr = {bookTable.getValueAt(i, 0).toString(), bookTable.getValueAt(i, 1).toString(), bookTable.getValueAt(i, 2).toString(), bookTable.getValueAt(i, 3).toString(), bookTable.getValueAt(i, 4).toString(), bookTable.getValueAt(i, 5).toString()};
                bookList.add(tmpStrArr);
            }
            
            try {
                File booksFile = new File("books.tmp");
                booksFile.delete();
                OutputStreamWriter osWriter = new OutputStreamWriter(new FileOutputStream("books.tmp"), "UTF-8");
                BufferedWriter bWriter = new BufferedWriter(osWriter);
                for(String[] str: bookList) {
                    bWriter.write(Arrays.toString(str) + System.lineSeparator());
                }
                bWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(NewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addButtonMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        if (removeButton.isEnabled()){
            int[] rows = bookTable.getSelectedRows();
            DefaultTableModel model = (DefaultTableModel)bookTable.getModel();
            for(int i = 0; i < rows.length; i++){
                model.removeRow(rows[i] - i);
            }
        }
    }//GEN-LAST:event_removeButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void bookTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookTableFocusLost

    }//GEN-LAST:event_bookTableFocusLost

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void checkOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutButtonMouseClicked
        CheckOut check = new CheckOut((String)bookTable.getValueAt(bookTable.getSelectedRow(), 0), (int)bookTable.getValueAt(bookTable.getSelectedRow(), 5));
        check.setVisible(true);
    }//GEN-LAST:event_checkOutButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Reopening login window...");
        LoginScreen login = new LoginScreen();
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void usersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersButtonMouseClicked
        UserPanel uPanel = new UserPanel();
        uPanel.setVisible(true);
    }//GEN-LAST:event_usersButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNSearch;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField authorSearch;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JToggleButton editButton;
    private javax.swing.JTextField genreSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton themeButton;
    private javax.swing.JTextField titleSearch;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
